export interface Blog {
    idBlog: string,
    catBlog: string,
    titleBlog: string,
    subtitleBlog: string,
    subtitleBlog01: string,
    subtitleBlog02: string,
    subtitleBlog03: string,
    subtitleBlog04: string,
    subtitleBlog05: string,
    bodyBlog: string,
    bodyBlog01: string,
    bodyBlog02: string,
    bodyBlog03: string,
    bodyBlog04: string,
    bodyBlog05: string,
    imageBlog: string,
    image: string,
    imageThumbBlog: string,
    thumbnail: string,
}
