export const PROFILE_DATA = {
  nameFull: "Carlos Sousa",
  ownerTitle: "Owner / Tech Guy",
  nameShort: "Carlos",
  nameShort2: "Sousa",
  bio: "Carlos is the owner & IT Guy at Geek2Go.ca. With over 25+ years of experience in the industry, Carlos has a passion for all things Tech...  Starting from the Commodore 64 in the 1980's to today's latest AI trends. He is dedicated to providing exceptional but simple service for his clients.",
  bio1: "A family friendly Tech Guy who has been in the Industry for 25+ years. Carlos was born in Toronto and for a while he seemed a little Robotic. It all changed when he heard Super Freak on Tarzan Dan.  He loves groovy tunes but has a soft spot for Gigabytes & Doo-Hickeys.  He eventually found his way to Burlington with the loves of his life...  Ellie, Daisy, Tania and Adele.  ",
  bio2: "Carlos started programming his Commodore 64 back in the 80s and has been doing it ever since.  He opened a \"Friendly Neighbourhood Computer Shop\" in Etobicoke in 1998 and proudly provided amazing service there for 15 years. In 2017 he moved to Burlington and started Geek2go.ca to provide top-notch IT services for individuals and businesses in the area.  When he's not working, you can find him spending time with his family, playing Video Games, losing at Chess, or exploring the latest tech trends.",
  bio3: "Carlos is a Funky DJ by night who also loves geek culture, Tech, Art & puts them all together at (Drum Roll Please) Geek2go.ca, FunkyRobot.ca & iSellcomics.ca.",
  businessName: "Geek2go.ca",
  ownerPhoto: "/assets/owner.jpg",
  ownerPhoto1: "/assets/owner2.jpg",
  ownerPhoto2: "/assets/owner1.jpg",
  bgPhoto: "assets/hero-background01.jpg",
  bgCTA: "assets/bg.jpg",
  logo: "assets/Geek2go-02.png",
  logo1: "assets/Geek2go-01.png",
  logo2: "assets/Geek2go-02.png",
  logo3: "assets/Geek2go-02.png",
  logo4: "assets/logo4.png",
  logo5: "assets/logo5.jpg",
  tagline: "IT Services for Everyone!",
  address: "Burlington, Ontario, Canada",   
  email: "carlos@geek2go.ca",
  phone: "(416) 832-3546",
  twitter: "https://twitter.com/funkyrobot73",
  facebook: "https://www.facebook.com/funkyrobot73",
  instagram: "https://www.instagram.com/funkyrobot73",
  tiktok: "https://www.tiktok.com/@funkyrobot73",
  youtube: "https://www.youtube.com/@funkyrobot73",
  youtubeChannel: "https://www.youtube.com/@funkyrobot73",
  youtubeVideo: "https://www.youtube.com/watch?v=_V8h76WyLSw",
  github: "https://www.github.com/funkyrobot73",
  linkedin: "https://www.linkedin.com/in/carlos-sousa-web/",  
  shortBlurb: "Geek2go.ca provides top-notch IT services for individuals and businesses in Burlington, Ontario. From website development to tech support, we have you covered.",
  photoboothBlurb: "Capture the moment with our state-of-the-art photo booth. With customizable backdrops, props, and instant prints, your guests will love taking home a piece of the fun!",
  djBlurb: "Our DJs are not just music players; they are entertainers who know how to read the crowd and keep the energy high. With a vast library of music spanning all genres, we can create the perfect playlist for your event.",
  videoBlurb: "Check out our latest events and behind-the-scenes action on our YouTube channel. Subscribe for tips, tricks, and inspiration for your next event!",
  testimonials: [ ],
  reviews: [],
  galleryRandom: [
    { src: "assets/sq/gallery01.png", alt: "Gallery Image 1" },
    { src: "assets/sq/gallery02.jpg", alt: "Gallery Image 2" },
    { src: "assets/sq/gallery3.jpg", alt: "Gallery Image 3" },
    { src: "assets/sq/gallery4.jpg", alt: "Gallery Image 4" },
    { src: "assets/sq/gallery5.jpg", alt: "Gallery Image 5" },
    { src: "assets/sq/gallery6.jpg", alt: "Gallery Image 6" },
    { src: "assets/sq/gallery7.jpg", alt: "Gallery Image 7" },
    { src: "assets/sq/gallery8.jpg", alt: "Gallery Image 8" },
    { src: "assets/sq/gallery9.jpg", alt: "Gallery Image 9" },
    { src: "assets/sq/gallery10.jpg", alt: "Gallery Image 10" },
    { src: "assets/sq/gallery11.jpg", alt: "Gallery Image 11" },
    { src: "assets/sq/gallery12.jpg", alt: "Gallery Image 12" }
  ],
  longBlurb: "Geek2go.ca is your one-stop shop for all things tech. Whether you're an individual looking for personal tech support or a business in need of comprehensive IT solutions, we've got you covered. Our team is passionate about music and entertainment, and we pride ourselves on our professionalism and attention to detail. We work closely with our clients to understand their vision and bring it to life. From website development and SEO to data security and cloud services, we offer a wide range of solutions designed to help you succeed in today's digital world. At Geek2go.ca, we believe that technology should be accessible to everyone, and we're committed to making that a reality. Contact us today to learn more about how we can help you achieve your tech goals.",
  aboutUs: "Funky Robot is a premier DJ and photo booth service based in Toronto, Canada. With years of experience in the industry, we know how to make your event unforgettable. Our team is passionate about music and entertainment, and we pride ourselves on our professionalism and attention to detail. We work closely with our clients to understand their vision and bring it to life. From weddings to corporate events, we have the expertise to make your event a success.",
  mission: "Our mission is to provide exceptional DJ and photo booth services that create unforgettable memories for our clients and their guests. We strive to exceed expectations with every event we handle, ensuring a fun and engaging atmosphere.",
  vision: "Our vision is to be the leading DJ and photo booth service in Toronto, known for our creativity, professionalism, and commitment to customer satisfaction. We aim to be the go-to choice for anyone looking to elevate their event with top-notch entertainment.",
  values: [
    "Customer Satisfaction",
    "Creativity",
    "Professionalism",
    "Integrity",
    "Fun"
  ],
  services: [
    "Website Development",
    "Wordpress Development",
    "SEO Services",
    "Google Ranking Improvement",
    "Virus Protection & Removal",
    "Data Security",
    "Data Backup & Recovery",
    "General Tech Support",
    "Graphic Design",
    "Social Media Management",
    "IT Consulting",
    "E-commerce Solutions",
    "Custom Software Development",
    "Network Setup & Maintenance",
    "Cloud Services",
    "Tech Training & Support",
    "More...!"
  ],
  services_more: [
     { title: 'Website Development', description: 'Professional music mixing for your event', icon: 'fas fa-music'},
     { title: 'Wordpress Development',description: 'Fun photo experiences for your guests', icon: 'fas fa-camera' },
     { title: 'SEO Services', description: 'Complete event entertainment solutions', icon: 'fas fa-star' },
      { title: 'Google Ranking Improvement', description: 'Improve your website visibility on Google', icon: 'fas fa-search' },
      { title: 'Virus Protection & Removal', description: 'Keep your systems safe from malware', icon: 'fas fa-shield-alt' },
      { title: 'Data Security', description: 'Protect your sensitive information', icon: 'fas fa-lock' },
      { title: 'Data Backup & Recovery', description: 'Ensure your data is always safe', icon: 'fas fa-database' },
      { title: 'General Tech Support', description: 'Get help with all your tech needs', icon: 'fas fa-headset' },
      { title: 'Graphic Design', description: 'Create stunning visuals for your brand', icon: 'fas fa-paint-brush' },
      { title: 'Social Media Management', description: 'Manage your social media presence', icon: 'fas fa-thumbs-up' },
      { title: 'IT Consulting', description: 'Expert advice for your IT strategy', icon: 'fas fa-lightbulb' },
      { title: 'E-commerce Solutions', description: 'Build and manage your online store', icon: 'fas fa-shopping-cart' },
      { title: 'Custom Software Development', description: 'Tailored software solutions for your business', icon: 'fas fa-code' },
      { title: 'Network Setup & Maintenance', description: 'Reliable network solutions', icon: 'fas fa-network-wired' },
      { title: 'Cloud Services', description: 'Leverage the power of the cloud', icon: 'fas fa-cloud' },
      { title: 'Tech Training & Support', description: 'Empower your team with tech skills', icon: 'fas fa-chalkboard-teacher' },
      { title: 'More...!', description: 'And much more to meet your tech needs', icon: 'fas fa-ellipsis-h' }
  ],
};
