export const PROFILE_DATA = {
  nameFull: "Carlos Sousa",
  ownerTitle: "Open Source Advocate & Developer",
  nameShort: "Carlos",
  nameShort2: "Sousa",
  bio: "Carlos is an open source advocate, developer, and custom scripting expert. With over 25+ years of industry experience, he started on the Commodore 64 in the 1980s and is passionate about helping people cut costs, recycle hardware, ditch expensive software licenses, and build fast custom code.",
  bio1: "A family-friendly developer and budget hacking expert with 25+ years in tech. Carlos ran a neighborhood shop in Etobicoke for 15 years before moving to Burlington. Today, he helps businesses and neighbors achieve digital independence through open-source alternatives, Linux clinics, and custom scripting.",
  bio2: "Carlos started programming his Commodore 64 back in the 80s and never stopped. After 15 successful years running his own shop in Etobicoke, he moved to Burlington in 2017 and launched Geek2go.ca. Today, he focuses on saving people money, setting up license-free software stacks, custom coding, and SEO. When he's not hacking together scripts, he's spending time with family, losing at Chess, or keeping his 'Funky Robot' DJ side-hustle alive.",
  bio3: "Carlos is a Tech Expert, a Funky DJ by night, and a lover of geek culture. He brings it all together at Geek2go.ca, FunkyRobot.ca, and iSellcomics.ca.",
  businessName: "Geek2go.ca",
  ownerPhoto: "/assets/owner.webp",
  ownerPhoto1: "/assets/owner2.webp",
  ownerPhoto2: "/assets/carlito.webp",
  bgPhoto: "assets/hero-background01.webp",
  bgCTA: "assets/bg.webp",
  logo: "assets/Geek2go-02.png",
  logo1: "assets/Geek2go-01.png",
  logo2: "assets/Geek2go-02.png",
  logo3: "assets/Geek2go-02.png",
  logo4: "assets/logo4.png",
  logo5: "assets/logo5.webp",
  tagline: "Open Source & Budget Tech for Everybody!",
  address: "Burlington, Ontario, Canada",   
  email: "carlos@geek2go.ca",
  phone: "(416) 832-3546",
  twitter: "https://twitter.com/funkyrobot73",
  transmissionsJsonUrl: "https://raw.githubusercontent.com/funkyrobot73/geek2go-feed/main/feed.json",
  facebook: "https://www.facebook.com/funkyrobot73",
  instagram: "https://www.instagram.com/funkyrobot73",
  tiktok: "https://www.tiktok.com/@funkyrobot73",
  youtube: "https://www.youtube.com/@funkyrobot73",
  youtubeChannel: "https://www.youtube.com/@funkyrobot73",
  youtubeVideo: "https://www.youtube.com/watch?v=_V8h76WyLSw",
  github: "https://www.github.com/funkyrobot73",
  linkedin: "https://www.linkedin.com/in/carlos-sousa-web/",  
  shortBlurb: "Geek2go.ca helps you cut licensing costs, recycle old hardware, and deploy custom coding, SEO, and Linux solutions. Open Source for Everybody!",
  photoboothBlurb: "Capture the moment with our state-of-the-art photo booth. With customizable backdrops, props, and instant prints, your guests will love taking home a piece of the fun!",
  djBlurb: "Our DJs are not just music players; they are entertainers who know how to read the crowd and keep the energy high. With a vast library of music spanning all genres, we can create the perfect playlist for your event.",
  videoBlurb: "Check out our latest events and behind-the-scenes action on our YouTube channel. Subscribe for tips, tricks, and inspiration for your next event!",
  testimonials: [ ],
  reviews: [],
  galleryRandom: [
    { src: "assets/sq/gallery01.png", alt: "Gallery Image 1" },
    { src: "assets/sq/gallery02.webp", alt: "Gallery Image 2" },
    { src: "assets/sq/gallery3.webp", alt: "Gallery Image 3" },
    { src: "assets/sq/gallery4.webp", alt: "Gallery Image 4" },
    { src: "assets/sq/gallery5.webp", alt: "Gallery Image 5" },
    { src: "assets/sq/gallery6.webp", alt: "Gallery Image 6" },
    { src: "assets/sq/gallery7.webp", alt: "Gallery Image 7" },
    { src: "assets/sq/gallery8.webp", alt: "Gallery Image 8" },
    { src: "assets/sq/gallery9.webp", alt: "Gallery Image 9" },
    { src: "assets/sq/gallery10.webp", alt: "Gallery Image 10" },
    { src: "assets/sq/gallery11.webp", alt: "Gallery Image 11" },
    { src: "assets/sq/gallery12.webp", alt: "Gallery Image 12" }
  ],
  longBlurb: "Geek2go.ca is your launchpad for digital independence. We believe that technology should be accessible, affordable, and license-free. Whether you need a custom website, high-impact SEO, or a complete 'De-Googled' open-source server to replace expensive monthly subscriptions, we have you covered. We work closely with our clients to reuse old hardware, build custom scripts, and transition workflows to Linux. At Geek2go.ca, we put 25+ years of coding and hacking expertise at your service. Contact us today to start saving money and owning your tech.",
  aboutUs: "Geek2Go.ca is where 25+ years of coding and open-source expertise meets budget-conscious tech hacking. Based in Burlington, I help individuals and businesses cut costs, ditch recurring licenses, and deploy custom scripts, websites, and SEO. My goal is to make open-source software work for everyone.",
  mission: "To empower my neighbors in Burlington and beyond to save money, reuse hardware, and achieve digital independence using high-quality open-source software, custom coding, and Linux.",
  vision: "To build a community of budget-conscious tech users who utilize open-source software, custom programs, and recycled hardware to defeat rising subscription fees.",
  values: [
    "Customer Satisfaction",
    "Creativity",
    "Professionalism",
    "Integrity",
    "Fun"
  ],
  services: [
    "Website Development",
    "Wordpress Development",
    "SEO Services",
    "Google Ranking Improvement",
    "Virus Protection & Removal",
    "Data Security",
    "Data Backup & Recovery",
    "General Tech Support",
    "Graphic Design",
    "Social Media Management",
    "IT Consulting",
    "E-commerce Solutions",
    "Custom Software Development",
    "Network Setup & Maintenance",
    "Cloud Services",
    "Tech Training & Support",
    "More...!"
  ],
  services_more: [
     { title: 'Website Development', description: 'Custom, modern web solutions tailored to your business goals.', icon: 'fas fa-code'},
     { title: 'Wordpress Development',description: 'Powerful, secure, and easy-to-manage WordPress sites.', icon: 'fab fa-wordpress' },
     { title: 'SEO Services', description: 'Data-driven strategies to boost your online visibility.', icon: 'fas fa-chart-line' },
      { title: 'Google Ranking Improvement', description: 'Technical optimizations to help you climb the search results.', icon: 'fas fa-search-plus' },
      { title: 'Virus Protection & Removal', description: 'Stay safe from malware and recover quickly from threats.', icon: 'fas fa-user-shield' },
      { title: 'Data Security', description: 'Robust protection for your sensitive personal and business data.', icon: 'fas fa-lock' },
      { title: 'Data Backup & Recovery', description: 'Reliable systems to ensure you never lose a single byte.', icon: 'fas fa-database' },
      { title: 'General Tech Support', description: 'Expert help for all your hardware and software headaches.', icon: 'fas fa-headset' },
      { title: 'Graphic Design', description: 'Clean, professional visuals that make your brand stand out.', icon: 'fas fa-paint-brush' },
      { title: 'Social Media Management', description: 'Engage your audience with consistent, creative content.', icon: 'fas fa-shoutout' },
      { title: 'IT Consulting', description: 'Strategic advice to help you leverage the best tech for growth.', icon: 'fas fa-lightbulb' },
      { title: 'E-commerce Solutions', description: 'Seamless online stores that make selling simple.', icon: 'fas fa-shopping-cart' },
      { title: 'Custom Software Development', description: 'Tailored applications built to solve your unique problems.', icon: 'fas fa-laptop-code' },
      { title: 'Network Setup & Maintenance', description: 'Fast, reliable, and secure connectivity for home or office.', icon: 'fas fa-network-wired' },
      { title: 'Cloud Services', description: 'Modern cloud solutions for collaboration and accessibility.', icon: 'fas fa-cloud' },
      { title: 'Tech Training & Support', description: 'Empowering you and your team to master the tools you use.', icon: 'fas fa-chalkboard-teacher' },
      { title: 'More...!', description: 'From smart homes to niche tech, I\'ve got you covered.', icon: 'fas fa-plus-circle' }
  ],
};
