export const PROFILE_DATA = {
  nameFull: "Carlos Sousa",
  ownerTitle: "Owner / Tech Guy",
  nameShort: "Carlos",
  nameShort2: "Sousa",
  bio: "Carlos is the owner & IT Guy at Geek2Go.ca. With over 25+ years of experience in the industry, Carlos has a passion for all things Tech...  Starting from the Commodore 64 in the 1980's to today's latest AI trends. He is dedicated to providing exceptional but simple service for his clients.",
  bio1: "A family-friendly Tech Guy who has been in the industry for 25+ years. Born and raised in Toronto with deep roots in Etobicoke (where he ran a neighborhood computer shop for 15 years), Carlos eventually found his way to Burlington with the loves of his life... Ellie, Daisy, Tania, and Adele. While he's an IT expert by day, he's always had a bit of a 'Funky' side, especially when 'Super Freak' comes on the radio.",
  bio2: "Carlos started programming his Commodore 64 back in the 80s and never stopped. After 15 successful years running his own shop in Etobicoke, he moved to Burlington in 2017 and launched Geek2go.ca. Today, he provides top-notch IT services for individuals and businesses across Burlington and Aldershot. When he's not solving tech puzzles, you can find him spending time with family, losing at Chess, or keeping his 'Funky Robot' DJ side-hustle alive.",
  bio3: "Carlos is a Tech Expert, a Funky DJ by night, and a lover of geek culture. He brings it all together at Geek2go.ca, FunkyRobot.ca, and iSellcomics.ca.",
  businessName: "Geek2go.ca",
  ownerPhoto: "/assets/owner.webp",
  ownerPhoto1: "/assets/owner2.webp",
  ownerPhoto2: "/assets/owner1.webp",
  bgPhoto: "assets/hero-background01.webp",
  bgCTA: "assets/bg.webp",
  logo: "assets/Geek2go-02.png",
  logo1: "assets/Geek2go-01.png",
  logo2: "assets/Geek2go-02.png",
  logo3: "assets/Geek2go-02.png",
  logo4: "assets/logo4.png",
  logo5: "assets/logo5.webp",
  tagline: "IT Services for Everyone!",
  address: "Burlington, Ontario, Canada",   
  email: "carlos@geek2go.ca",
  phone: "(416) 832-3546",
  twitter: "https://twitter.com/funkyrobot73",
  facebook: "https://www.facebook.com/funkyrobot73",
  instagram: "https://www.instagram.com/funkyrobot73",
  tiktok: "https://www.tiktok.com/@funkyrobot73",
  youtube: "https://www.youtube.com/@funkyrobot73",
  youtubeChannel: "https://www.youtube.com/@funkyrobot73",
  youtubeVideo: "https://www.youtube.com/watch?v=_V8h76WyLSw",
  github: "https://www.github.com/funkyrobot73",
  linkedin: "https://www.linkedin.com/in/carlos-sousa-web/",  
  shortBlurb: "Geek2go.ca provides top-notch IT services for individuals and businesses in Burlington, Ontario. From website development to tech support, we have you covered.",
  photoboothBlurb: "Capture the moment with our state-of-the-art photo booth. With customizable backdrops, props, and instant prints, your guests will love taking home a piece of the fun!",
  djBlurb: "Our DJs are not just music players; they are entertainers who know how to read the crowd and keep the energy high. With a vast library of music spanning all genres, we can create the perfect playlist for your event.",
  videoBlurb: "Check out our latest events and behind-the-scenes action on our YouTube channel. Subscribe for tips, tricks, and inspiration for your next event!",
  testimonials: [ ],
  reviews: [],
  galleryRandom: [
    { src: "assets/sq/gallery01.png", alt: "Gallery Image 1" },
    { src: "assets/sq/gallery02.webp", alt: "Gallery Image 2" },
    { src: "assets/sq/gallery3.webp", alt: "Gallery Image 3" },
    { src: "assets/sq/gallery4.webp", alt: "Gallery Image 4" },
    { src: "assets/sq/gallery5.webp", alt: "Gallery Image 5" },
    { src: "assets/sq/gallery6.webp", alt: "Gallery Image 6" },
    { src: "assets/sq/gallery7.webp", alt: "Gallery Image 7" },
    { src: "assets/sq/gallery8.webp", alt: "Gallery Image 8" },
    { src: "assets/sq/gallery9.webp", alt: "Gallery Image 9" },
    { src: "assets/sq/gallery10.webp", alt: "Gallery Image 10" },
    { src: "assets/sq/gallery11.webp", alt: "Gallery Image 11" },
    { src: "assets/sq/gallery12.webp", alt: "Gallery Image 12" }
  ],
  longBlurb: "Geek2go.ca is your one-stop shop for all things tech. Whether you're an individual looking for personal tech support or a business in need of comprehensive IT solutions, we've got you covered. Our team is passionate about music and entertainment, and we pride ourselves on our professionalism and attention to detail. We work closely with our clients to understand their vision and bring it to life. From website development and SEO to data security and cloud services, we offer a wide range of solutions designed to help you succeed in today's digital world. At Geek2go.ca, we believe that technology should be accessible to everyone, and we're committed to making that a reality. Contact us today to learn more about how we can help you achieve your tech goals.",
  aboutUs: "Geek2Go.ca is where 25+ years of IT expertise meets a passion for creative technology. Based in Burlington and serving the Aldershot area, I provide uncomplicated, expert-level tech support for individuals and small businesses. Whether I'm troubleshooting a network by day or keeping things funky as a DJ by night, my goal is always the same: making technology work for you, not against you.",
  mission: "To provide exceptional, approachable IT services that take the stress out of technology for my neighbours in Burlington and beyond. I strive to exceed expectations with every project, ensuring a reliable and engaging experience.",
  vision: "To be the most trusted local 'Tech Guy' in Burlington, known for reliable solutions, creative energy, and a commitment to keeping technology simple and fun.",
  values: [
    "Customer Satisfaction",
    "Creativity",
    "Professionalism",
    "Integrity",
    "Fun"
  ],
  services: [
    "Website Development",
    "Wordpress Development",
    "SEO Services",
    "Google Ranking Improvement",
    "Virus Protection & Removal",
    "Data Security",
    "Data Backup & Recovery",
    "General Tech Support",
    "Graphic Design",
    "Social Media Management",
    "IT Consulting",
    "E-commerce Solutions",
    "Custom Software Development",
    "Network Setup & Maintenance",
    "Cloud Services",
    "Tech Training & Support",
    "More...!"
  ],
  services_more: [
     { title: 'Website Development', description: 'Custom, modern web solutions tailored to your business goals.', icon: 'fas fa-code'},
     { title: 'Wordpress Development',description: 'Powerful, secure, and easy-to-manage WordPress sites.', icon: 'fab fa-wordpress' },
     { title: 'SEO Services', description: 'Data-driven strategies to boost your online visibility.', icon: 'fas fa-chart-line' },
      { title: 'Google Ranking Improvement', description: 'Technical optimizations to help you climb the search results.', icon: 'fas fa-search-plus' },
      { title: 'Virus Protection & Removal', description: 'Stay safe from malware and recover quickly from threats.', icon: 'fas fa-user-shield' },
      { title: 'Data Security', description: 'Robust protection for your sensitive personal and business data.', icon: 'fas fa-lock' },
      { title: 'Data Backup & Recovery', description: 'Reliable systems to ensure you never lose a single byte.', icon: 'fas fa-database' },
      { title: 'General Tech Support', description: 'Expert help for all your hardware and software headaches.', icon: 'fas fa-headset' },
      { title: 'Graphic Design', description: 'Clean, professional visuals that make your brand stand out.', icon: 'fas fa-paint-brush' },
      { title: 'Social Media Management', description: 'Engage your audience with consistent, creative content.', icon: 'fas fa-shoutout' },
      { title: 'IT Consulting', description: 'Strategic advice to help you leverage the best tech for growth.', icon: 'fas fa-lightbulb' },
      { title: 'E-commerce Solutions', description: 'Seamless online stores that make selling simple.', icon: 'fas fa-shopping-cart' },
      { title: 'Custom Software Development', description: 'Tailored applications built to solve your unique problems.', icon: 'fas fa-laptop-code' },
      { title: 'Network Setup & Maintenance', description: 'Fast, reliable, and secure connectivity for home or office.', icon: 'fas fa-network-wired' },
      { title: 'Cloud Services', description: 'Modern cloud solutions for collaboration and accessibility.', icon: 'fas fa-cloud' },
      { title: 'Tech Training & Support', description: 'Empowering you and your team to master the tools you use.', icon: 'fas fa-chalkboard-teacher' },
      { title: 'More...!', description: 'From smart homes to niche tech, I\'ve got you covered.', icon: 'fas fa-plus-circle' }
  ],
};
