name: Deploy to cPanel

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout your code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Build Angular project
    - name: Build project
      run: npm run build -- --configuration production --output-path=dist/geek2go

    # Step 5: Deploy to cPanel via FTP
    - name: Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/geek2go/browser/
        server-dir: ./
        dangerous-clean-slate: true